os: linux
dist: bionic
sudo: required

language: cpp
compiler: g++

install:
    - sudo apt-get update -y
    - sudo apt-get install -y python-pip
    - python -m pip install cpplint
    - sudo apt-get install -y cppcheck

script:
    - ./ci/hw1/linters.sh
    - ./ci/hw1/build.sh
