os: linux
dist: bionic

language: cpp
compiler: clang

stages:
    - linters
    - build

jobs:
    include:
        stage: linters
        script:
            - echo none
        stage: build
        script:
            - echo none
